added server initialization
avehun/time_memorizer pull request #1
Opened 2024-04-14 13:30 UTC by radiance822

2024-04-17 06:13 UTC, DemiurgUrr requested changes
Хорошо, что реализовал модели, но лучше добавить ещё реализацию ручек сразу. 
И пробовал запустить?

2024-04-17 06:13 UTC, DemiurgUrr commented on internal/app/time_memorizer/service.go
> +	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
А для чего оставил этот хэндлер? В самом сервисе он не нужен, но можно туда добавить документацию, если хочется оставить

2024-04-17 06:13 UTC, DemiurgUrr commented on api/protos/timeMemorizer.proto
> +    rpc simpleResponse(Message) returns (Message) {}
Ручки сервиса пока не описывал?

2024-04-17 06:13 UTC, DemiurgUrr commented on internal/pkg/app/app.go
> +	if err := mux.Serve(); err != nil {
Это лишнее, достаточно запустить два сервера

2024-04-17 06:13 UTC, DemiurgUrr commented on api/protos/timeMemorizer.proto
> +    rpc simpleResponse(Message) returns (Message) {}
И поменяй, пожалуйста, на большую букву название - мелочь, но единообразие нужно соблюдать

2024-04-17 06:13 UTC, DemiurgUrr commented on internal/pkg/app/app.go
> +	if err := http.Serve(listener, mux); err != nil {
Тут нет привязки  http сервера к ручкам service.Server

2024-04-17 06:13 UTC, DemiurgUrr commented on internal/app/model/model.go
> +	_, ok := cs[category]
Тут можно сократить в одну строчку 
`cs[category]=cs[category]+time`, так как даже если нет, то мапа вернёт дефолтный 0, который не повлияет на сумму

2024-04-17 06:13 UTC, DemiurgUrr commented on internal/app/model/model.go
> +	if time > val {
Здесь, я так понимаю, time это какая-то сумма трат, лучше переименовать, так как снижает читаемость кода, не понятно, что за время

2024-04-17 06:13 UTC, DemiurgUrr commented on internal/app/time_memorizer/service.go
> +	panic("unimplemented")
Тут ты сразу обозначаешь, что у тебя в любом случае выдаёт unimplemented, хотя ручку уже реализовал, может забыл удалить?

2024-04-17 06:13 UTC, DemiurgUrr commented on internal/pkg/app/app.go
> +	grpcListener := mux.Match(cmux.HTTP2())
А почему решил использовать именно cmux?

2024-04-20 10:50 UTC, radiance822 commented
> И пробовал запустить?

2024-06-02 08:19 UTC, merged